# Generated by Django 3.0.4 on 2020-03-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('mainContent', models.CharField(max_length=10000)),
                ('url', models.CharField(default='none', max_length=200)),
            ],
        ),
    ]
