# Generated by Django 3.0.4 on 2020-03-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogconf',
            name='url',
            field=models.CharField(default='', max_length=50),
        ),
    ]
