# Generated by Django 3.0.4 on 2020-03-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20200310_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blogtitle',
            field=models.CharField(default='<blogtitle>', max_length=100),
        ),
    ]
