# Generated by Django 3.0.4 on 2020-03-12 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_auto_20200310_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogconf',
            old_name='sidenote',
            new_name='description',
        ),
    ]
